// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/[post].tsx";
import * as $1 from "./routes/_404.tsx";
import * as $2 from "./routes/_app.tsx";
import * as $3 from "./routes/api/r1.ts";
import * as $4 from "./routes/index.tsx";
import * as $$0 from "./islands/Main.tsx";

const manifest = {
  routes: {
    "./routes/[post].tsx": $0,
    "./routes/_404.tsx": $1,
    "./routes/_app.tsx": $2,
    "./routes/api/r1.ts": $3,
    "./routes/index.tsx": $4,
  },
  islands: {
    "./islands/Main.tsx": $$0,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
